import fs from "fs";

const posts = [
    {
        id: 1,
        timestamp: "2024-10-14 00:00:01.000000",
        user_id: 3,
        title: "Smooth loading dots animation with CSS",
        description: "Add a touch of flair to your loading screens with this minimal, elegant loading dots animation! Using only CSS, this snippet creates a bouncing dot animation where each dot has a slight delay, creating a smooth, dynamic loading effect. Perfect for web projects needing an extra hint of sophistication, this snippet is easily customizable, lightweight, and simple to implement for any loading state on your site.",
        thumbnail: "/media/code-1.mov",
        html: fs.readFileSync('seeds/code-1/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-1/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-1/main.js', 'utf8'),
        likes: 138
    },
    {
        id: 2,
        timestamp: "2024-04-01 00:00:01.000000",
        user_id: 2,
        title: "Floating yogi with smooth mouse follow and bounce animation.",
        description: "Add a touch of playfulness to your site with this floating yogi icon that smoothly follows the user’s mouse movements on the Y-axis and features a subtle bounce animation. Though it showcases a yoga icon here, this flexible snippet can be repurposed for other fun themes, like rockets, astronauts, or floating objects. With minimal CSS and JavaScript, it’s an easy way to introduce an interactive, engaging element to any web project!",
        thumbnail: "/media/code-2.mov",
        html: fs.readFileSync('seeds/code-2/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-2/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-2/main.js', 'utf8'),
        likes: 97
    },
    {
        id: 3,
        timestamp: "2024-10-10 00:00:01.000000",
        user_id: 3,
        title: "Beginner-friendly Express server setup in just a few lines",
        description: "This Express.js setup is a straightforward starting point for beginners, containing everything you need for a basic server. It includes JSON parsing with express.json() and a simple GET route at the root ('/') that responds with a UTF-8 encoded 'Hello world!' message to confirm the server is running. The app.listen() function starts the server on a specified port and logs the server URL for easy access. This template provides the fundamental setup needed to start building APIs or adding routes, making it a versatile and beginner-friendly foundation.",
        thumbnail: "/media/code-3.png",
        html: fs.readFileSync('seeds/code-3/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-3/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-3/main.js', 'utf8'),
        likes: 112
    },
    {
        id: 4,
        timestamp: "2024-10-07 00:00:01.000000",
        user_id: 4,
        title: "Dynamic starry night effect with customizable twinkling stars",
        description: "This JavaScript and CSS snippet creates a starry night effect with twinkling stars, perfect for adding an animated background to any webpage. Easily customize the count variable to adjust the number of stars, modify the size variable to change star dimensions, or fine-tune animation-duration and animation-delay to control the twinkling speed. Additionally, the background and box-shadow properties allow for custom star colors and glow effects, making this snippet adaptable to a range of themes and designs.",
        thumbnail: "/media/code-4.mov",
        html: fs.readFileSync('seeds/code-4/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-4/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-4/main.js', 'utf8'),
        likes: 76
    },
    {
        id: 5,
        timestamp: "2024-09-15 00:00:01.000000",
        user_id: 5,
        title: "Setting up Multer with unique file names for media storage",
        description: "This setup uses Multer with disk storage to handle media uploads in the backend, ideal for storing images or videos. The diskStorage configuration specifies a destination folder and leverages a uniqueName format for filenames, generated by combining a timestamp with the original filename. This unique naming system prevents file conflicts, ensuring each upload has a distinct name, which is particularly useful for applications handling multiple media files. This configuration provides a solid foundation for integrating file upload capabilities, making it easy to expand with routes for handling file uploads in Express.",
        thumbnail: "/media/code-5.png",
        html: fs.readFileSync('seeds/code-5/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-5/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-5/main.js', 'utf8'),
        likes: 142
    },
    {
        id: 6,
        timestamp: "2024-07-25 00:00:01.000000",
        user_id: 6,
        title: "Flashing discount banner",
        description: "This pure CSS snippet creates an eye-catching discount banner with a flashing background effect, perfect for promoting special offers. Using keyframes, the background color of the discount text alternates between dark grey and a vibrant blue, drawing attention to the discount code displayed. With no JavaScript required, this lightweight setup is easy to implement and customize by adjusting colors, font sizes, or animation timing. This snippet is ideal for highlighting promotions and enhancing user engagement with minimal code.",
        thumbnail: "/media/code-6.mov",
        html: fs.readFileSync('seeds/code-6/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-6/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-6/main.js', 'utf8'),
        likes: 95
    },
    {
        id: 7,
        timestamp: "2024-07-01 00:00:01.000000",
        user_id: 7,
        title: "Snowflake icons with spinning hover effect",
        description: "This simple CSS snippet brings snowflake icons to life with a smooth spinning effect on hover, adding a fun, interactive touch to your page. The snowflakes come in three sizes (small, medium, large) for added visual interest, and each spins in a gentle, continuous rotation when hovered over. Perfect for holiday or winter themes, this effect is easy to use and requires no JavaScript, making it a quick and festive addition to any webpage.",
        thumbnail: "/media/code-7.mov",
        html: fs.readFileSync('seeds/code-7/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-7/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-7/main.js', 'utf8'),
        likes: 108
    },
    {
        id: 8,
        timestamp: "2024-10-27 00:00:01.000000",
        user_id: 1,
        title: "Scroll-activated sliding sidebar with social icons",
        description: "This CSS and JavaScript snippet creates a sliding sidebar navigation that appears only after scrolling, adding a sleek and interactive touch to your page. The sidebar, positioned on the right, holds social media icons and stays hidden until the user scrolls past a specific point, then smoothly slides into view. The sidebar’s opacity and position adjust on scroll, making it subtle yet engaging. This effect is ideal for keeping the interface clean and bringing in social links only when users start exploring the content, and it’s easy to customize by adjusting scroll offset, animation speed, and icon styles.",
        thumbnail: "/media/code-8.mov",
        html: fs.readFileSync('seeds/code-8/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-8/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-8/main.js', 'utf8'),
        likes: 125
    },
    {
        id: 9,
        timestamp: "2024-09-01 00:00:01.000000",
        user_id: 4,
        title: "Simple monochrome mode toggle with color inversion",
        description: "This quick JavaScript and CSS snippet toggles between light and dark modes by inverting colors, perfect for monochrome or minimalist designs. With one click, users can switch modes, and preferences are saved in local storage for future visits. Note: This technique is best suited for sites with primarily black-and-white elements, as it will invert all colors on the page, potentially distorting more colorful designs. Ideal for adding basic dark mode functionality with minimal code!",
        thumbnail: "/media/code-9.mov",
        html: fs.readFileSync('seeds/code-9/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-9/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-9/main.js', 'utf8'),
        likes: 67
    },
    {
        id: 10,
        timestamp: "2024-05-09 00:00:01.000000",
        user_id: 2,
        title: "Stylish offset button with active animation effect",
        description: "This CSS-only snippet creates a stylish offset button with a bold background and outline effect, perfect for call-to-action links like 'Shop Now.' The button has a layered look, with a background color slightly offset from the outline. When clicked, the button animates with a smooth translate effect, creating a 'press down' look. This design is ideal for adding an interactive, visually striking button to your site and is easy to customize by adjusting colors, padding, and animation offset for different themes or actions.",
        thumbnail: "/media/code-10.mov",
        html: fs.readFileSync('seeds/code-10/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-10/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-10/main.js', 'utf8'),
        likes: 88
    },
    {
        id: 11,
        timestamp: "2024-08-18 00:00:01.000000",
        user_id: 6,
        title: "Product card layout with shadow and responsive grid",
        description: "This CSS layout creates an organized, visually appealing product card grid for showcasing items. Each product card includes an image, title, and price, styled with a soft box shadow and rounded corners for a modern look. The grid layout is responsive and adapts to different screen sizes, while flex properties ensure each card aligns neatly. This setup is perfect for product pages, portfolios, or feature showcases and can be easily customized by adjusting colors, font sizes, and shadow intensity for different design themes.",
        thumbnail: "/media/code-11.png",
        html: fs.readFileSync('seeds/code-11/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-11/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-11/main.js', 'utf8'),
        likes: 134
    },
    {
        id: 12,
        timestamp: "2024-10-27 00:00:01.000000",
        user_id: 5,
        title: "Interactive trivia card with 3D flip effect",
        description: "This CSS-only snippet creates an interactive trivia card that flips 180 degrees on hover to reveal the answer. The card has a front and back side, each styled with bold colors and a smooth 3D transition. The flip effect is managed by the flip-card-inner element, while backface-visibility ensures a seamless transition without background overlap. Perfect for quizzes, trivia, or any interactive content, this design is easy to customize by adjusting colors, dimensions, and border styles to fit various themes.",
        thumbnail: "/media/code-12.mov",
        html: fs.readFileSync('seeds/code-12/index.html', 'utf8'),
        css: fs.readFileSync('seeds/code-12/style.css', 'utf8'),
        js:  fs.readFileSync('seeds/code-12/main.js', 'utf8'),
        likes: 149
    }
];

export default posts;